### PR TITLE
Feature/frontend

### PR DESCRIPTION
**Pull request by Hailey1005**
Implementation of front-end

### CODE REVIEW

**Review by josmoo — DISMISSED** [review]
It looks really good; I like it a lot! There seems to be unnecessary scroll bars on the transaction page that might be worth looking at though.

**Review by fneedly — CHANGES_REQUESTED** [review]
Can you create a `.gitignore` file in the base frontend directory and put `*/.DS_Store` and `.vscode/` into it? Then, delete the DS_Store files and the .vscode directory from github

**Comment by Hailey1005** [comment]
@gschick3 done it!

**Review by fneedly — APPROVED** [review]
Looks good now

**Review by josmoo — APPROVED** [review]

**Pull request merged**
